### ISSUE TITLE
Error with Completion Exception from Ender Dragon Fight Remastered

### ISSUE THREAD

**Issue by suerion** [MrGenie151/Ender-Dragon-Fight-Remastered#35]
### Describe the bug

Hey, i got some issues on my side with completionException:
Fabric 1.21.1 on 0.16.5
```
[15:29:01] [main/ERROR]: Failed to load function endfight:tick
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 9: Could not parse command: Mixin transformation of net.minecraft.command.argument.MessageArgumentType$MessageFormat failed at position 93: ...o run say <--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at MC/net.minecraft.resource.ProfiledResourceReload.method_18357(ProfiledResourceReload.java:35) ~[server-intermediary.jar:?]
        at MC/net.minecraft.resource.SimpleResourceReload.method_18371(SimpleResourceReload.java:62) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 9: Could not parse command: Mixin transformation of net.minecraft.command.argument.MessageArgumentType$MessageFormat failed at position 93: ...o run say <--[HERE]
        at MC/net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 8 more
[15:29:01] [main/ERROR]: Couldn't load tag minecraft:tick as it is missing following references: endfight:tick (from mr_edf_remastered), hcrplus:main (from mr_hardcore_revivereloaded)
```

### Steps to reproduce

Hugh Modpack Server Log:
https://mclo.gs/iKlXez6

### Expected behavior

Commands should work fine.

### Additional context

Could a Compat issue with 
https://modrinth.com/datapack/edf-remastered
https://modrinth.com/datapack/true-ending

**Comment by suerion** [comment]
Hey, was fixed with the update of this mod

https://github.com/DrexHD/WorldGameRules/issues/1
